default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: reading_list_development

test:
  <<: *default
  database: reading_list_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "reading_list_production") %>
